//! WirePlumber 0.5+ integration for routing application streams before their
//! first link is created.
//!
//! A fixed Lua policy hook is installed in WirePlumber's user data directory
//! and enabled by a configuration fragment. The hook reads the current route
//! map from the `sonux.routes.v1` key on subject 0 of WirePlumber's `default`
//! metadata object. Assignment changes therefore do not require a WirePlumber
//! restart; only installing the hook for the first time does.

use std::path::{Path, PathBuf};

use serde::Serialize;

use crate::error::SinkError;
use crate::persistence::assignments::{Assignment, Assignments};
use crate::persistence::seen::SeenApps;

pub const ROUTES_METADATA_KEY: &str = "sonux.routes.v1";
pub const ROUTES_METADATA_TYPE: &str = "Spa:String:JSON";
pub const ROUTES_ACK_METADATA_KEY: &str = "sonux.routes.ack.v1";
pub const ROUTES_READY_METADATA_KEY: &str = "sonux.routes.ready.v1";
pub const ROUTES_CLEAR_ACK: &str = "cleared";

const COMPONENT_CONF: &str = r#"# Generated by Sonux (audio mixer). Do not edit.
wireplumber.components = [
  {
    name = sonux-routing.lua, type = script/lua
    provides = hooks.sonux.routing
    requires = [ metadata.default, policy.linking.standard ]
  }
]

wireplumber.profiles = {
  main = {
    hooks.sonux.routing = required
  }
}
"#;

const ROUTING_SCRIPT: &str = include_str!("../../assets/wireplumber/sonux-routing.lua");

#[derive(Serialize)]
struct RoutesMetadata<'a> {
    version: u8,
    routes: Vec<&'a Assignment>,
}

pub fn routes_metadata_value(
    assignments: &Assignments,
    seen: &SeenApps,
) -> Result<String, SinkError> {
    serde_json::to_string(&RoutesMetadata {
        version: 1,
        routes: assignments
            .assignments
            .iter()
            .filter(|route| !seen.is_ignored(&route.match_prop, &route.match_value))
            .collect(),
    })
    .map_err(|error| SinkError::Config(format!("serialize WirePlumber routes: {error}")))
}

fn named_conf_path(config_dir: &Path, name: &str) -> PathBuf {
    config_dir
        .join("wireplumber")
        .join("wireplumber.conf.d")
        .join(name)
}

fn conf_path_from(config_dir: &Path) -> PathBuf {
    named_conf_path(config_dir, "90-sonux-routing.conf")
}

fn script_path_from(data_dir: &Path) -> PathBuf {
    data_dir
        .join("wireplumber")
        .join("scripts")
        .join("sonux-routing.lua")
}

pub fn conf_path() -> Result<PathBuf, SinkError> {
    let dir = dirs::config_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user config directory".into()))?;
    Ok(conf_path_from(&dir))
}

pub fn script_path() -> Result<PathBuf, SinkError> {
    let dir = dirs::data_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user data directory".into()))?;
    Ok(script_path_from(&dir))
}

fn install_at(config_dir: &Path, data_dir: &Path) -> Result<(), SinkError> {
    let script = script_path_from(data_dir);
    if let Some(parent) = script.parent() {
        super::ensure_private_dir(parent)?;
    }
    // Install the dependency first. A failed second write can leave an unused
    // script, but never a component that points at a missing script.
    super::write_atomic(&script, ROUTING_SCRIPT)?;

    let conf = conf_path_from(config_dir);
    if let Some(parent) = conf.parent() {
        super::ensure_private_dir(parent)?;
    }
    super::write_atomic(&conf, COMPONENT_CONF)?;
    Ok(())
}

fn migrate_at(config_dir: &Path, data_dir: &Path) -> Result<(), SinkError> {
    install_at(config_dir, data_dir)?;
    let legacy = named_conf_path(config_dir, "90-sink-routing.conf");
    if legacy.exists() {
        super::remove_file(&legacy)?;
    }
    Ok(())
}

/// Replace the legacy generated `stream.rules` fragment with the fixed policy
/// component and remove the pre-Sonux filename after installation succeeds.
pub fn migrate_legacy_conf() -> Result<(), SinkError> {
    let config_dir = dirs::config_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user config directory".into()))?;
    let data_dir = dirs::data_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user data directory".into()))?;
    migrate_at(&config_dir, &data_dir)
}

/// Ensure the fixed WirePlumber integration is installed. The route map itself
/// is published through PipeWire metadata by the audio backend; it is not
/// rendered into this startup-only configuration.
pub fn write(_assignments: &Assignments) -> Result<(), SinkError> {
    let config_dir = dirs::config_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user config directory".into()))?;
    let data_dir = dirs::data_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user data directory".into()))?;
    install_at(&config_dir, &data_dir)
}

/// Remove both files owned by this integration. Missing files are harmless so
/// factory reset can be retried after a partial cleanup.
pub fn remove_installation() -> Result<(), SinkError> {
    for path in [conf_path()?, script_path()?] {
        if path.exists() {
            super::remove_file(&path)?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn temp_root(label: &str) -> PathBuf {
        std::env::temp_dir().join(format!(
            "sonux-wireplumber-{label}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|duration| duration.as_nanos())
                .unwrap_or(0)
        ))
    }

    #[test]
    fn serializes_versioned_metadata_including_empty_routes() {
        let empty = routes_metadata_value(&Assignments::default(), &SeenApps::default()).unwrap();
        assert_eq!(empty, r#"{"version":1,"routes":[]}"#);

        let mut assignments = Assignments::default();
        assignments.set("application.name", "Brave", "sink_media");
        let value: serde_json::Value = serde_json::from_str(
            &routes_metadata_value(&assignments, &SeenApps::default()).unwrap(),
        )
        .unwrap();
        assert_eq!(value["version"], 1);
        assert_eq!(value["routes"][0]["match_prop"], "application.name");
        assert_eq!(value["routes"][0]["match_value"], "Brave");
        assert_eq!(value["routes"][0]["sink_name"], "sink_media");

        let mut seen = SeenApps::default();
        seen.upsert("application.name", "Brave", "Brave", None, None, 1);
        assert!(seen.set_ignored("application.name", "Brave", true));
        assert_eq!(
            routes_metadata_value(&assignments, &seen).unwrap(),
            r#"{"version":1,"routes":[]}"#
        );
    }

    #[test]
    fn installs_fixed_component_and_embedded_hook() {
        let root = temp_root("install");
        let config = root.join("config");
        let data = root.join("data");

        install_at(&config, &data).unwrap();

        let conf = fs::read_to_string(conf_path_from(&config)).unwrap();
        assert_eq!(conf, COMPONENT_CONF);
        assert!(conf.contains("hooks.sonux.routing = required"));
        assert!(!conf.contains("stream.rules"));

        let script = fs::read_to_string(script_path_from(&data)).unwrap();
        assert_eq!(script, ROUTING_SCRIPT);
        assert!(script.contains(ROUTES_METADATA_KEY));
        assert!(script.contains("\"linking/find-defined-target\""));
        assert!(script.contains("stream_props [\"media.class\"] ~= \"Stream/Output/Audio\""));
        assert!(script.contains("target_props [\"sonux.owner\"] == \"sonux\""));

        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn installation_replaces_old_generated_stream_rules() {
        let root = temp_root("replace");
        let config = root.join("config");
        let data = root.join("data");
        let path = conf_path_from(&config);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, "stream.rules = [ { old = true } ]\n").unwrap();

        install_at(&config, &data).unwrap();

        assert_eq!(fs::read_to_string(path).unwrap(), COMPONENT_CONF);
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn migration_removes_pre_sonux_fragment_after_installing_replacement() {
        let root = temp_root("migrate");
        let config = root.join("config");
        let data = root.join("data");
        let legacy = named_conf_path(&config, "90-sink-routing.conf");
        fs::create_dir_all(legacy.parent().unwrap()).unwrap();
        fs::write(&legacy, "old routing rules\n").unwrap();

        migrate_at(&config, &data).unwrap();

        assert!(!legacy.exists());
        assert_eq!(
            fs::read_to_string(conf_path_from(&config)).unwrap(),
            COMPONENT_CONF
        );
        assert_eq!(
            fs::read_to_string(script_path_from(&data)).unwrap(),
            ROUTING_SCRIPT
        );
        let _ = fs::remove_dir_all(root);
    }

    #[cfg(unix)]
    #[test]
    fn installation_directories_are_owner_only() {
        use std::os::unix::fs::PermissionsExt;

        let root = temp_root("permissions");
        let config = root.join("config");
        let data = root.join("data");
        install_at(&config, &data).unwrap();

        for path in [conf_path_from(&config), script_path_from(&data)] {
            let parent_mode = fs::metadata(path.parent().unwrap())
                .unwrap()
                .permissions()
                .mode()
                & 0o777;
            assert_eq!(parent_mode, 0o700);
        }

        let _ = fs::remove_dir_all(root);
    }
}
